### ISSUE TITLE
How to download the dataset

### ISSUE THREAD

**Issue by guoxiaolu** [MarkoArsenovic/DeepLearning_PlantDiseases#1]
Impressive job, I have noticed that you'v got a state-of-art result, it is impressive. But I cannot download the dataset from the given PlantVillage link. I have found that https://plantvillage.org/posts/7127 , it seems that the dataset cannot be accessed now. Can you give me more information about the dataset? Thank you very much

**Comment by MarkoArsenovic** [comment]
Thank you. This is the reason why I have provided the link to the preprocessed dataset in **README.md** from [PlantVillage](https://plantvillage.org/) used in this work, dataset can be downloaded from [here](https://drive.google.com/open?id=0B_voCy5O5sXMTFByemhpZllYREU).<br/>
Note, that you should respect their license, and use/cite the dataset due to that.

**Comment by guoxiaolu** [comment]
Sorry for wasting your time, I've just noticed it in README.
I have checked the dataset, and I found the "background" seems no relation to plant disease. Do you think it is useful for this classification task? I'm doubted about it.
Thank you.
